### PR TITLE
Homework4 Extra Feature Test

### PR DESCRIPTION
**Pull request by richardbreslin**

### CODE REVIEW

**Comment by Elyasmusa** [comment]
The home page looks alot cleaner with importing the steamID into it

**Comment by richardbreslin** [comment]
Will remove the Example STEAM ID's but other than that good

**Comment by MuneebFKhan** [comment]
Nice work making the home page look more simple and easy to use

**Comment by mohammedali101** [comment]
Example Steam ID was removed because there is a link that the user can go to in order to understand how their ID must be. The webpage still works perfectly.

**Pull request merged**
