### PR TITLE
Error Page Test Implementation

### PR DESCRIPTION
**Pull request by richardbreslin**

### CODE REVIEW

**Comment by Elyasmusa** [comment]
Error handling for the steam ID is better now with its functionality

**Comment by richardbreslin** [comment]
Very good

**Comment by MuneebFKhan** [comment]
Error page looks good, it shows the message that user needs 17 digits for a valid id

**Comment by mohammedali101** [comment]
Error page works exceptionally. If the user enters a string/char variable or enters an ID that is less than or greater than 17 it will be incorrect. We did a great job handling the error page.

**Pull request merged**
